# theme: jekyll-theme-minimal
remote_theme: marella/jekyll-theme-documentation

permalink: pretty
nav:
- Intro to Tapis and Workflows:
  - Intro to Tapis: ./block1/01-intro-to-tapis
  - Intro to Workflows: ./block1/05-intro-to-workflows
- Intro to Jupyter:
  - Introduction to Jupyter: ./block1/intro-to-jupyter
  - Starting a Jupyter Notebook: ./block1/intro-to-jupyter#starting-up-your-jupyter-notebook-environment
  - Creating a Notebook: ./block1/intro-to-jupyter#creating-a-notebook  
- Tapis Systems:
  - Intro to Tapis Systems: ./block1/02-systems
- Tapis Apps:
  - Intro to Apps: ./block1/03-apps
- Tapis Jobs:
  - Intro to Tapis Jobs: ./block1/04-jobs
# - Notebook:
#   - Notebook: ./block1/Tapis_workflows_mpm.ipynb

theme: jekyll-theme-minimal
