remote_theme: marella/jekyll-theme-documentation
#remote_theme: pawamoy/jekyll-readthedocs

#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

permalink: pretty
nav:
  - Welcome and Background:
    - Welcome: ''
  - Intro to Tapis:
    - Intro to Tapis(Agave): block1/tapis-intro
  - Intro to Systems:
    - Intro to Tapis Systems: block1/tapis-systems
  - Intro to Apps:
    - Intro to Apps: block1/apps
  - Intro to Jobs:
    - Intro to Tapis Jobs with Aloe: block1/jobs
